remote_theme: just-the-docs/just-the-docs

title: Climatolog√≠a Chilena

color_scheme: dark

search_enable: true

last_edit_timestamp: true

aux_links_path: _includes/team_widget.html

aux_links: 
  "Ver en Github":
   - "https://github.com/juaco-21/Proyect_IMT2200_Idea"
    
exclude:
  - src/
  - data/       
  - notebooks/
  - assets/
