remote_theme: just-the-docs/just-the-docs

title: ClimatologÃ­a Chilena

color_scheme: dark

search_enable: true

last_edit_timestamp: true

aux_links: 
  "Ver en Github":
    - "https://github.com/juaco-21/Proyect_IMT2200_Idea"
  "Equipo: ":
    # ğŸš¨ NOTA: Tienes que usar HTML dentro del Markdown aquÃ­ ğŸš¨
    # Cada lÃ­nea es un elemento en la barra.
    - '<div style="text-align: center; margin: 10px 0;">'
    - '  <img src="figures/members-faces/joaquin.jpg" alt="Joaquin Ortuzar" style="width: 80px; height: 80px; border-radius: 50%; border: 2px solid #007bff;">'
    - '  <br><a href="https://github.com/juaco-21">**Joaquin Ortuzar**</a>'
    - '</div>'

exclude:
  - src/
  - data/       
  - notebooks/ 
  - figures/ 
